### ISSUE TITLE
MAX_TICKS is not defined

### ISSUE THREAD

**Issue by evgenart** [arista-eosext/PCAPDecoder#5]
Hi, I'm getting this error, the MAX_TICKS is actually not defined, what value should it be?

# pcaptd -r --output-file dump_hiprec_ts.pcap  dump.pcap

Decoding timestamps...

Traceback (most recent call last):
  File "/usr/local/bin/pcaptd", line 594, in <module>
    main()
  File "/usr/local/bin/pcaptd", line 587, in main
    opts.fcs)
  File "/usr/local/bin/pcaptd", line 521, in _readPcap
    ts = _decodeTimestamps(pcapTs, hwTicks, devId)
  File "/usr/local/bin/pcaptd", line 419, in _decodeTimestamps
    hwDelta += MAX_TICKS
NameError: name 'MAX_TICKS' is not defined

**Comment by evgenart** [comment]
sorry it seems, for some reason I've had a corrupted file copied
